version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: shop
      APP_USER_PASSWORD: shop
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

  user-service:
    build: .
    container_name: user-service
    depends_on:
      - oracle
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: shop
      SPRING_DATASOURCE_PASSWORD: shop
      JWT_SECRET: ton-secret-ici
    ports:
      - "8080:8080"

volumes:
  oracle-data:
